version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jkn-plus:latest
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
